apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: auth-service
          image: ghcr.io/ednasx/auth-service:latest
          ports:
            - containerPort: 3001
            