apiVersion: batch/v1
kind: Job
metadata:
  name: auth-migrate
  labels:
    app: auth-service
    component: migration
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: auth-migrate
        component: migration
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: auth-migrate
          image: ghcr.io/ednasx/auth-service:d9400bf894026926d44e19fe0f1ade8af16cfe68
          imagePullPolicy: IfNotPresent
          command: ["node", "src/database/migrate.js"]
          envFrom:
            - configMapRef:
                name: auth-config
            - secretRef:
                name: auth-secret
